services:
  runner:
    build: .
    restart: unless-stopped
    networks:
      - backend
      - dind-network
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 3
      resources:
        reservations:
          cpus: "0.5"
          memory: 1024M
  cache:
    image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      - '3000:3000'
    environment:
      API_BASE_URL: http://cache:3000
    volumes:
      - cache:/app/.data

volumes:
  cache:

networks:
    dind-network:
        external: true
    backend:
        external: false